### ISSUE TITLE
Config file in backup

### ISSUE THREAD

**Issue by Goten87** [cranstonide/linux-minecraft-scripts#2]
hello m8
i have tested the cron option for backup in my server
and its not working he cant find the config file
so its not working at all

and u need to have in all you files `source ./mc-config.cfg`
else it wil not load in

**Comment by mide** [comment]
I do run `source mc-config.cfg` in every one of my scripts. It could be a relative path issue, but I'm not sure. I will look into it soon.

**Comment by mide** [comment]
The most recent commits should fix it. It was indeed a problem with relative paths.
