### ISSUE TITLE
add the jar to the config file

### ISSUE THREAD

**Issue by Goten87** [cranstonide/linux-minecraft-scripts#3]
u need to add the .jar to the config file like i have becose when people have there minecraft modded u dont start up with `minecraft_server.jar`
but with somthing else like me i need to start my minecraft with the `minecraftforge-universal.jar` file
so i have a var in the mc-config.cfg  `jar="minecraftforge-universal"`

**Comment by mide** [comment]
If this (and the other two issues) were one pull request, I could merge them in so much easier. Not sure why you made three issues. I'll add the jar in the config file.

**Comment by mide** [comment]
This feature has been added. Keep in mind, my scripts were never designed to run on anything but Vanilla Minecraft.
